// retrieve the images generated by the emotion
if(type == 'emotionbase') {
    drawGallery(emotionValue, gender, `${gender}/${emotionValue}`);
}
else {  // userbase
    drawGallery(emotionValue, gender, `${userId}/${emotionValue}`);
}       